-- Publisher durable state -- ARCHITECTURE_REMEDIATION.md A1.2, A1.3.
--
-- Single source of truth for both tables the worker and API share across the
-- process boundary that didn't exist before this plan (findings 1, 2, 3).
-- Applied automatically by postgres's docker-entrypoint-initdb.d on first
-- container start (see docker-compose.yml); re-run manually otherwise:
--   psql "$DATABASE_URL" -f platform/db/schema.sql

-- output_refs: artifact_kind -> {sha256, media_type, size}. A hash alone
-- can't rehydrate a StageResult on a cache hit -- ArtifactRef requires
-- media_type and size too, so the cached record carries what it takes to
-- reconstruct one without re-deriving it from the blob.
CREATE TABLE IF NOT EXISTS cache_index (
    cache_key    TEXT PRIMARY KEY,
    stage        TEXT NOT NULL,
    version      INTEGER NOT NULL,
    output_refs  JSONB NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    hit_count    INTEGER NOT NULL DEFAULT 0,
    last_hit_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS builds (
    id            TEXT PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    document_id   TEXT NOT NULL,
    design_id     TEXT,
    profile_ids   JSONB,
    mode          TEXT NOT NULL DEFAULT 'proof',
    status        TEXT NOT NULL DEFAULT 'queued',  -- queued|running|completed|failed|dead
    error_kind    TEXT,
    error_message TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    -- U1 (docs/ARCHITECTURE_UPLIFT_PLAN.md): lease-based worker durability.
    -- A build left at 'running' by a killed worker is reclaimable once its
    -- lease expires; `attempt` counts claims so a poison build dead-letters
    -- after MAX_ATTEMPTS instead of looping; `worker_id` names who holds the
    -- lease. Applied idempotently for databases created before this plan.
    attempt          INTEGER NOT NULL DEFAULT 0,
    lease_expires_at TIMESTAMPTZ,
    worker_id        TEXT,
    -- U7: correlation id generated by the API on POST /v1/builds and put on
    -- every worker log record -- one id joins an HTTP request to a container's
    -- stdout.
    correlation_id   TEXT
);

-- Idempotent upgrade for databases created before U1/U2: fresh databases get
-- the columns from the CREATE TABLE above; existing ones need the ALTER.
-- MUST run before builds_reclaimable_idx below, which references
-- lease_expires_at.
ALTER TABLE builds ADD COLUMN IF NOT EXISTS attempt INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS worker_id TEXT;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS correlation_id TEXT;

-- U7: builds.error_kind is a constrained set (StageError.kind enum values plus
-- the worker's own INTERNAL/exhausted markers) so failure-mode counts are
-- queryable instead of free-text. Drop-then-add is idempotent.
ALTER TABLE builds DROP CONSTRAINT IF EXISTS builds_error_kind_check;
ALTER TABLE builds ADD CONSTRAINT builds_error_kind_check CHECK (
    error_kind IS NULL OR error_kind IN (
        'bad_input', 'policy_violation', 'engine_bug', 'infra',
        'external_limit', 'INTERNAL', 'exhausted'
    )
);

CREATE INDEX IF NOT EXISTS builds_tenant_idx ON builds (tenant_id);
-- Admission and the worker's claim query both filter status='queued' ordered
-- by age; a plain scan over every build ever created doesn't scale past a
-- handful of rows.
CREATE INDEX IF NOT EXISTS builds_queued_idx ON builds (created_at) WHERE status = 'queued';
-- U1: the reclaim side of the claim query -- expired leases on 'running' rows.
CREATE INDEX IF NOT EXISTS builds_reclaimable_idx
    ON builds (lease_expires_at) WHERE status = 'running';

CREATE TABLE IF NOT EXISTS build_stages (
    build_id      TEXT NOT NULL REFERENCES builds(id),
    stage_name    TEXT NOT NULL,
    stage_version INTEGER NOT NULL,
    status        TEXT NOT NULL,  -- running|completed|failed
    cache_hit     BOOLEAN NOT NULL DEFAULT FALSE,
    duration_ms   INTEGER,
    metrics       JSONB,
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    PRIMARY KEY (build_id, stage_name)
);

-- A2.1 -- the API's in-memory Map()s (titles, manuscripts, idempotency
-- replay, webhooks). Same shape as the TS interfaces in packages/api/src/
-- index.ts; tenant_id is load-bearing on every one so the existing
-- assertTenant() checks survive the move off in-memory state unchanged.

CREATE TABLE IF NOT EXISTS titles (
    id         TEXT PRIMARY KEY,
    tenant_id  TEXT NOT NULL,
    title      TEXT NOT NULL,
    author     TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS titles_tenant_idx ON titles (tenant_id);

CREATE TABLE IF NOT EXISTS manuscripts (
    id               TEXT PRIMARY KEY,
    tenant_id        TEXT NOT NULL,
    title_id         TEXT NOT NULL REFERENCES titles(id),
    status           TEXT NOT NULL DEFAULT 'uploaded',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- U2 (docs/ARCHITECTURE_UPLIFT_PLAN.md): the CAS sha256 of the uploaded
    -- manuscript bytes. NULL until PUT /v1/manuscripts/:id/upload stores
    -- them; a build of a manuscript with no stored source is refused with
    -- BAD_INPUT rather than silently substituted with a fixture.
    source_sha256    TEXT,
    source_size      BIGINT,
    source_media_type TEXT
);
CREATE INDEX IF NOT EXISTS manuscripts_tenant_idx ON manuscripts (tenant_id);

-- U2 upgrade for databases created before manuscript upload existed.
ALTER TABLE manuscripts ADD COLUMN IF NOT EXISTS source_sha256 TEXT;
ALTER TABLE manuscripts ADD COLUMN IF NOT EXISTS source_size BIGINT;
ALTER TABLE manuscripts ADD COLUMN IF NOT EXISTS source_media_type TEXT;

-- Idempotency-Key replay: a retried POST/PATCH with the same key (scoped to
-- tenant, so two tenants cannot collide on or read each other's keys)
-- returns the first response instead of creating a second resource.
CREATE TABLE IF NOT EXISTS idempotency_keys (
    tenant_id    TEXT NOT NULL,
    idem_key     TEXT NOT NULL,
    status_code  INTEGER NOT NULL,
    body         JSONB NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, idem_key)
);

CREATE TABLE IF NOT EXISTS webhooks (
    id         TEXT PRIMARY KEY,
    tenant_id  TEXT NOT NULL,
    url        TEXT NOT NULL,
    events     JSONB NOT NULL,
    secret     TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS webhooks_tenant_idx ON webhooks (tenant_id);

-- An artifact is identified by its SCHEMA ID, not by `kind`.
--
-- `kind` is stage-LOCAL: it is the key inside one stage's `outputs={}` dict, so
-- it is only unique within that stage. Two stages legitimately both emit
-- kind='pdf' (paginate -> raw-pdf/1, finish -> pdfx/1) and three emit
-- kind='report'. With PRIMARY KEY (build_id, kind) plus the worker's
-- ON CONFLICT DO NOTHING, the FIRST stage to finish won and every later
-- artifact of the same kind was silently dropped -- so `pdf` resolved to
-- paginate's unconverted weasyprint output and the API served it as the
-- press-ready file, while the real PDF/X-1a from `finish` was discarded.
-- Preflight's report lost to finish's report the same way.
--
-- schema_id is the identity the DAG itself already runs on (one stage's output
-- schema matched to another's input schema), and it is globally unique.
CREATE TABLE IF NOT EXISTS artifacts (
    build_id   TEXT NOT NULL REFERENCES builds(id),
    kind       TEXT NOT NULL,
    schema_id  TEXT NOT NULL,
    sha256     TEXT NOT NULL,
    media_type TEXT NOT NULL,
    size       BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (build_id, schema_id)
);
CREATE INDEX IF NOT EXISTS artifacts_kind_idx ON artifacts (build_id, kind);
