"""
Real Ghostscript invocation -- PDF/X-1a press conversion and proof generation.

Until now BOTH finish stages (`stages/finish_stage.py` and `finish-gs` in
`stages/prepress_stages.py`) merely *detected* whether `gs` was on PATH and
then passed the input through unconverted. They were correctly gated behind
`allow_stub_engines` so they never lied about it -- but that gate meant no
real build could ever complete, because the worker runs with
allow_stub_engines=False by design.

This module is the missing piece: it actually runs Ghostscript. Both stages
call it, so press conversion has one implementation, not two that can drift
(the same constraint A4.2 puts on the shared AST->HTML renderer).

Two distinct outputs, per BUILD_PLAN.md §3.10 / O4:
  - PRESS: PDF/X-1a, CMYK, full fidelity, OutputIntent installed. For the vendor.
  - PROOF: downsampled, linearized (fast-web-view). For the human reviewer.
Never one compromise file serving both.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Optional

# Ghostscript's -dPDFX alone does NOT produce a conformant PDF/X file: the
# standard requires an OutputIntent naming the destination colour profile, and
# gs will reject the job without one. This PostScript prologue installs it.
# Ghostscript reads it before the input PDF.
PDFX_DEF_TEMPLATE = """%!
% PDF/X-1a definition -- generated by publisher_prepress.ghostscript.
% Do not edit by hand; this file is written per-build into the work dir.

/ICCProfile ({icc_profile}) def

[ /Title ({title})
  /DOCINFO pdfmark

[/_objdef {{icc_PDFX}} /type /stream /OBJ pdfmark
[{{icc_PDFX}} <</N 4>> /PUT pdfmark
[{{icc_PDFX}} ICCProfile (r) file /PUT pdfmark

[/_objdef {{OutputIntent_PDFX}} /type /dict /OBJ pdfmark
[{{OutputIntent_PDFX}} <<
  /Type /OutputIntent
  /S /GTS_PDFX
  /OutputCondition ({output_condition})
  /Info ({output_condition})
  /OutputConditionIdentifier ({condition_id})
  /RegistryName (http://www.color.org)
  /DestOutputProfile {{icc_PDFX}}
>> /PUT pdfmark
[{{Catalog}} <</OutputIntents [ {{OutputIntent_PDFX}} ]>> /PUT pdfmark
"""

# Where Debian/Alpine ghostscript packages keep their bundled ICC profiles.
_ICC_SEARCH_GLOBS = (
    "/usr/share/ghostscript/*/iccprofiles/default_cmyk.icc",
    "/usr/share/ghostscript/iccprofiles/default_cmyk.icc",
    "/usr/share/color/icc/ghostscript/default_cmyk.icc",
)


class GhostscriptError(RuntimeError):
    """Ghostscript ran and failed. Carries its stderr -- gs is chatty on error."""


def find_binary() -> Optional[str]:
    """Absolute path to the gs binary, or None. Windows names it differently."""
    return shutil.which("gs") or shutil.which("gswin64c") or shutil.which("gswin32c")


def find_cmyk_icc() -> Optional[Path]:
    """
    Locate a CMYK ICC profile for the OutputIntent.

    A per-vendor profile (Lightning Source, KDP, IngramSpark each publish one)
    is the eventual goal; gs's bundled default_cmyk.icc is a valid, standards-
    conformant stand-in that makes the output genuinely PDF/X-1a today.
    """
    for pattern in _ICC_SEARCH_GLOBS:
        root = Path(pattern).anchor
        rel = pattern[len(root):]
        matches = sorted(Path(root).glob(rel))
        if matches:
            return matches[0]
    return None


def _run(cmd: list[str], timeout: int = 300) -> None:
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise GhostscriptError(
            f"ghostscript exited {result.returncode}\n"
            f"command: {' '.join(cmd)}\n"
            f"stderr: {result.stderr.strip()}"
        )


def _assert_pdf(path: Path, what: str) -> None:
    """Ghostscript can exit 0 having written nothing useful. Verify the bytes."""
    if not path.exists() or path.stat().st_size == 0:
        raise GhostscriptError(f"{what}: ghostscript exited 0 but wrote no output to {path}")
    if path.read_bytes()[:4] != b"%PDF":
        raise GhostscriptError(f"{what}: output at {path} is not a PDF")


def to_pdfx(
    input_pdf: Path,
    output_pdf: Path,
    work_dir: Path,
    *,
    title: str = "Untitled",
    output_condition: str = "Commercial and specialty offset printing",
    condition_id: str = "CGATS TR 001",
    gs_binary: Optional[str] = None,
) -> None:
    """
    Convert to PDF/X-1a: CMYK, prepress-quality, OutputIntent installed.

    Raises GhostscriptError if gs is missing, the ICC profile cannot be found,
    gs fails, or the output is not a PDF. It never returns having produced
    something less than what it claims -- a silently-unconverted "press" PDF
    is the exact failure mode this whole module exists to remove.
    """
    gs = gs_binary or find_binary()
    if gs is None:
        raise GhostscriptError("ghostscript binary not found on PATH")

    icc = find_cmyk_icc()
    if icc is None:
        raise GhostscriptError(
            "no CMYK ICC profile found -- PDF/X-1a requires an OutputIntent "
            f"destination profile. Searched: {', '.join(_ICC_SEARCH_GLOBS)}"
        )

    # PostScript string literals delimit with parens, so unescaped parens in a
    # book title would terminate the literal early and corrupt the prologue.
    def _ps_escape(s: str) -> str:
        return s.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")

    work_dir.mkdir(parents=True, exist_ok=True)
    pdfx_def = work_dir / "PDFX_def.ps"
    pdfx_def.write_text(
        PDFX_DEF_TEMPLATE.format(
            icc_profile=str(icc).replace("\\", "/"),
            title=_ps_escape(title),
            output_condition=_ps_escape(output_condition),
            condition_id=_ps_escape(condition_id),
        ),
        encoding="utf-8",
    )

    _run([
        gs,
        "-dPDFX",
        "-dBATCH",
        "-dNOPAUSE",
        "-dNOOUTERSAVE",
        "-sDEVICE=pdfwrite",
        "-dPDFSETTINGS=/prepress",
        "-sColorConversionStrategy=CMYK",
        "-dProcessColorModel=/DeviceCMYK",
        # SAFER is left ON (gs 10's default). The input PDF is rendered from
        # user manuscript content, so relaxing it would widen the blast radius
        # of a malicious document. The prologue needs to read exactly one file
        # -- the ICC profile -- so permit exactly that one.
        f"--permit-file-read={icc}",
        f"-sOutputFile={output_pdf}",
        str(pdfx_def),
        str(input_pdf),
    ])
    _assert_pdf(output_pdf, "press")


def to_proof(
    input_pdf: Path,
    output_pdf: Path,
    *,
    dpi: int = 150,
    gs_binary: Optional[str] = None,
) -> None:
    """
    Produce the reviewer's proof: downsampled images, linearized for fast
    web view. Deliberately NOT the press file -- smaller and faster to open,
    and not something anyone should mistake for vendor-ready output.
    """
    gs = gs_binary or find_binary()
    if gs is None:
        raise GhostscriptError("ghostscript binary not found on PATH")

    _run([
        gs,
        "-dBATCH",
        "-dNOPAUSE",
        "-sDEVICE=pdfwrite",
        "-dPDFSETTINGS=/ebook",
        "-dDownsampleColorImages=true",
        "-dDownsampleGrayImages=true",
        f"-dColorImageResolution={dpi}",
        f"-dGrayImageResolution={dpi}",
        "-dFastWebView=true",
        f"-sOutputFile={output_pdf}",
        str(input_pdf),
    ])
    _assert_pdf(output_pdf, "proof")
