"""
Real Ghostscript invocation -- PDF/X-1a press conversion and proof generation.

Until now BOTH finish stages (`stages/finish_stage.py` and `finish-gs` in
`stages/prepress_stages.py`) merely *detected* whether `gs` was on PATH and
then passed the input through unconverted. They were correctly gated behind
`allow_stub_engines` so they never lied about it -- but that gate meant no
real build could ever complete, because the worker runs with
allow_stub_engines=False by design.

This module is the missing piece: it actually runs Ghostscript. Both stages
call it, so press conversion has one implementation, not two that can drift
(the same constraint A4.2 puts on the shared AST->HTML renderer).

Two distinct outputs, per BUILD_PLAN.md §3.10 / O4:
  - PRESS: PDF/X-1a, CMYK, full fidelity, OutputIntent installed. For the vendor.
  - PROOF: downsampled, linearized (fast-web-view). For the human reviewer.
Never one compromise file serving both.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Optional

# Ghostscript's -dPDFX alone does NOT produce a conformant PDF/X file: the
# standard requires an OutputIntent naming the destination colour profile, and
# gs will reject the job without one. This PostScript prologue installs it.
# Ghostscript reads it before the input PDF.
PDFX_DEF_TEMPLATE = """%!
% PDF/X-1a definition -- generated by publisher_prepress.ghostscript.
% Do not edit by hand; this file is written per-build into the work dir.

% Box geometry. PDF/X requires TrimBox <= BleedBox <= MediaBox. Left to derive
% these itself, Ghostscript produced a BleedBox the TrimBox did not fit inside,
% then abandoned PDF/X and STILL exited 0. These are array-valued distiller
% params, which `-d` cannot express (`-dPDFXTrimBoxToMediaBoxOffset=[0 0 0 0]`
% makes gs exit 1), so they are set here in PostScript instead.
%
% BleedBoxToTrimBoxOffset carries the SAME figure as the trim offset, so the
% BleedBox is the TrimBox grown back out to exactly the MediaBox. Writing
% [0 0 0 0] here instead -- and relying on PDFXSetBleedBoxToMediaBox to widen it
% -- collapsed BleedBox onto TrimBox, and gs then failed its own
% TrimBox-fits-inside-BleedBox test on two identical non-integral rectangles.
% That is the same floating-point equality bug documented at the -dUseTrimBox
% call site below; the fix is to leave no pair of boxes exactly equal.
<<
  /PDFXSetBleedBoxToMediaBox true
  /PDFXTrimBoxToMediaBoxOffset [{trim_offset}]
  /PDFXBleedBoxToTrimBoxOffset [{bleed_offset}]
>> setdistillerparams

/ICCProfile ({icc_profile}) def

[ /Title ({title})
  /DOCINFO pdfmark

[/_objdef {{icc_PDFX}} /type /stream /OBJ pdfmark
[{{icc_PDFX}} <</N 4>> /PUT pdfmark
[{{icc_PDFX}} ICCProfile (r) file /PUT pdfmark

[/_objdef {{OutputIntent_PDFX}} /type /dict /OBJ pdfmark
[{{OutputIntent_PDFX}} <<
  /Type /OutputIntent
  /S /GTS_PDFX
  /OutputCondition ({output_condition})
  /Info ({output_condition})
  /OutputConditionIdentifier ({condition_id})
  /RegistryName (http://www.color.org)
  /DestOutputProfile {{icc_PDFX}}
>> /PUT pdfmark
[{{Catalog}} <</OutputIntents [ {{OutputIntent_PDFX}} ]>> /PUT pdfmark
"""

# Explicit override, checked first: a vendor-supplied profile (Lightning Source,
# KDP and IngramSpark each publish one) belongs here rather than in this list.
_ICC_ENV = "PUBLISHER_CMYK_ICC"

# Where ghostscript keeps its bundled ICC profiles, per packaging. The Windows
# entries are not decoration: `find_binary` has always known gs is named
# differently there, but this list was Debian-only, so finish-gs failed on any
# Windows host with "no CMYK ICC profile found" while the profile sat in the
# install directory.
_ICC_SEARCH_GLOBS = (
    # Debian / Alpine / most Linux packaging
    "/usr/share/ghostscript/*/iccprofiles/default_cmyk.icc",
    "/usr/share/ghostscript/iccprofiles/default_cmyk.icc",
    "/usr/share/color/icc/ghostscript/default_cmyk.icc",
    # macOS Homebrew
    "/usr/local/share/ghostscript/*/iccprofiles/default_cmyk.icc",
    "/opt/homebrew/share/ghostscript/*/iccprofiles/default_cmyk.icc",
    # Windows: the official MSI, and scoop (whose `gs` is a shim in a different
    # tree from the app, so the binary's own path leads nowhere useful).
    "C:/Program Files/gs/*/iccprofiles/default_cmyk.icc",
    "C:/Program Files (x86)/gs/*/iccprofiles/default_cmyk.icc",
    "~/scoop/apps/ghostscript/current/iccprofiles/default_cmyk.icc",
    "~/scoop/apps/ghostscript/*/iccprofiles/default_cmyk.icc",
)


class GhostscriptError(RuntimeError):
    """Ghostscript ran and failed. Carries its stderr -- gs is chatty on error."""


def find_binary() -> Optional[str]:
    """Absolute path to the gs binary, or None. Windows names it differently."""
    return shutil.which("gs") or shutil.which("gswin64c") or shutil.which("gswin32c")


def find_cmyk_icc() -> Optional[Path]:
    """
    Locate a CMYK ICC profile for the OutputIntent.

    A per-vendor profile (Lightning Source, KDP, IngramSpark each publish one)
    is the eventual goal; gs's bundled default_cmyk.icc is a valid, standards-
    conformant stand-in that makes the output genuinely PDF/X-1a today.

    Order: explicit override, then the gs install tree the binary sits in, then
    the per-platform locations. The binary-relative step is what makes an
    install in an unusual prefix work without configuration.
    """
    override = os.environ.get(_ICC_ENV)
    if override:
        path = Path(override).expanduser()
        if path.is_file():
            return path
        raise GhostscriptError(
            f"{_ICC_ENV} points at {override!r}, which is not a file. Refusing to "
            f"fall back to a different profile: the OutputIntent names the "
            f"printing condition the book is being proofed for, and silently "
            f"substituting another one misstates it."
        )

    binary = find_binary()
    if binary:
        # .../bin/gswin64c.exe -> .../iccprofiles, and one level further up for
        # layouts that put the binary two deep.
        base = Path(binary).resolve().parent
        for ancestor in (base, base.parent, base.parent.parent):
            candidate = ancestor / "iccprofiles" / "default_cmyk.icc"
            if candidate.is_file():
                return candidate

    for pattern in _ICC_SEARCH_GLOBS:
        expanded = str(Path(pattern).expanduser())
        root = Path(expanded).anchor
        matches = sorted(Path(root).glob(expanded[len(root):])) if root else []
        if matches:
            return matches[0]
    return None


def _run(cmd: list[str], timeout: int = 300) -> str:
    """Run gs and return its combined output.

    The output is RETURNED, not discarded, because Ghostscript reports PDF/X
    non-conformance on a successful exit -- see _assert_no_pdfx_downgrade.
    """
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise GhostscriptError(
            f"ghostscript exited {result.returncode}\n"
            f"command: {' '.join(cmd)}\n"
            f"stderr: {result.stderr.strip()}"
        )
    return f"{result.stdout}\n{result.stderr}"


# Ghostscript does not fail the job when it cannot honour -dPDFX. It prints a
# reason, silently writes an ordinary PDF, and exits 0. Reading only the exit
# code is therefore indistinguishable from success -- which is how a build came
# to report `"profileApplied": "pdfx-1a"` over bytes gs had explicitly declined
# to make PDF/X. These are the phrases it uses to say so.
_PDFX_DOWNGRADE_MARKERS = (
    "reverting to normal PDF output",
    "not permitted in PDF/X",
    "cannot be represented in PDF/X",
)


def _assert_no_pdfx_downgrade(gs_output: str) -> None:
    for marker in _PDFX_DOWNGRADE_MARKERS:
        if marker in gs_output:
            detail = next(
                (ln.strip() for ln in gs_output.splitlines() if marker in ln), marker
            )
            raise GhostscriptError(
                "ghostscript declined to produce PDF/X and fell back to ordinary "
                f"PDF output: {detail}"
            )


def _assert_pdf(path: Path, what: str) -> None:
    """Ghostscript can exit 0 having written nothing useful. Verify the bytes."""
    if not path.exists() or path.stat().st_size == 0:
        raise GhostscriptError(f"{what}: ghostscript exited 0 but wrote no output to {path}")
    if path.read_bytes()[:4] != b"%PDF":
        raise GhostscriptError(f"{what}: output at {path} is not a PDF")


def _assert_pdfx(path: Path) -> None:
    """
    Post-condition: the bytes on disk really carry a PDF/X OutputIntent.

    A file-type check (`%PDF`) cannot tell a press-ready PDF/X-1a from the
    unconverted input, so on its own it lets the exact substitution this module
    exists to prevent pass as success. pdfwrite emits the OutputIntent dict and
    its /GTS_PDFX subtype uncompressed, so a byte scan is sufficient and needs
    no PDF parser.
    """
    data = path.read_bytes()
    missing = [m.decode() for m in (b"/GTS_PDFX", b"/OutputIntent") if m not in data]
    if missing:
        raise GhostscriptError(
            f"output at {path} is not PDF/X: no {', '.join(missing)} in the file. "
            "The OutputIntent prologue did not take effect; refusing to certify "
            "this as press-ready."
        )


def to_pdfx(
    input_pdf: Path,
    output_pdf: Path,
    work_dir: Path,
    *,
    title: str = "Untitled",
    output_condition: str = "Commercial and specialty offset printing",
    condition_id: str = "CGATS TR 001",
    bleed_pt: float = 0.0,
    gs_binary: Optional[str] = None,
) -> None:
    """
    Convert to PDF/X-1a: CMYK, prepress-quality, OutputIntent installed.

    `bleed_pt` is the bleed allowance already present in the INPUT's page box,
    in points. PDF/X requires TrimBox to sit inside BleedBox; this sets
    BleedBox = MediaBox and insets TrimBox from it by `bleed_pt` on every side.
    The default of 0 collapses all three boxes onto MediaBox, which is the
    honest description of a render carrying no bleed allowance -- it does not
    fabricate a bleed the pages do not have. Whether that is acceptable for a
    given vendor is preflight's judgement to make, not this function's.

    Note that Ghostscript applies those offsets only to boxes the input LACKS.
    weasyprint always writes all three, so for anything this pipeline renders
    the boxes come from the CSS (`@page { bleed: ... }`, emitted by
    design-compile) and `bleed_pt` merely has to agree with them. The offsets
    still matter for inputs that carry a MediaBox alone.

    Raises GhostscriptError if gs is missing, the ICC profile cannot be found,
    gs fails, gs declines PDF/X, or the output carries no OutputIntent. It never
    returns having produced something less than what it claims -- a silently-
    unconverted "press" PDF is the exact failure mode this module exists to
    remove.
    """
    if bleed_pt < 0:
        raise GhostscriptError(f"bleed_pt must not be negative, got {bleed_pt}")
    gs = gs_binary or find_binary()
    if gs is None:
        raise GhostscriptError("ghostscript binary not found on PATH")

    icc = find_cmyk_icc()
    if icc is None:
        raise GhostscriptError(
            "no CMYK ICC profile found -- PDF/X-1a requires an OutputIntent "
            f"destination profile. Searched: {', '.join(_ICC_SEARCH_GLOBS)}"
        )

    # PostScript string literals delimit with parens, so unescaped parens in a
    # book title would terminate the literal early and corrupt the prologue.
    def _ps_escape(s: str) -> str:
        return s.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")

    work_dir.mkdir(parents=True, exist_ok=True)
    pdfx_def = work_dir / "PDFX_def.ps"
    pdfx_def.write_text(
        PDFX_DEF_TEMPLATE.format(
            icc_profile=str(icc).replace("\\", "/"),
            trim_offset=" ".join([f"{bleed_pt:g}"] * 4),
            bleed_offset=" ".join([f"{bleed_pt:g}"] * 4),
            title=_ps_escape(title),
            output_condition=_ps_escape(output_condition),
            condition_id=_ps_escape(condition_id),
        ),
        encoding="utf-8",
    )

    # A render with no bleed allowance has MediaBox == TrimBox == BleedBox, and
    # Ghostscript STILL rejected it ("TrimBox does not fit inside BleedBox") --
    # its own comparison of identical non-integral box coordinates
    # (0 0 430.866142 649.133858) does not survive the round trip. -dUseTrimBox
    # makes the page exactly the TrimBox, so there is nothing left to compare
    # unequally. That is only correct while the boxes ARE identical: with a real
    # bleed allowance it would crop the bleed away, so it is applied only then.
    box_args = ["-dPDFXSetBleedBoxToMediaBox=true"]
    if bleed_pt == 0:
        box_args.append("-dUseTrimBox=true")

    gs_output = _run([
        gs,
        "-dPDFX",
        *box_args,
        "-dBATCH",
        "-dNOPAUSE",
        "-dNOOUTERSAVE",
        "-sDEVICE=pdfwrite",
        "-dPDFSETTINGS=/prepress",
        "-sColorConversionStrategy=CMYK",
        "-dProcessColorModel=/DeviceCMYK",
        # SAFER is left ON (gs 10's default). The input PDF is rendered from
        # user manuscript content, so relaxing it would widen the blast radius
        # of a malicious document. The prologue needs to read exactly one file
        # -- the ICC profile -- so permit exactly that one.
        f"--permit-file-read={icc}",
        f"-sOutputFile={output_pdf}",
        str(pdfx_def),
        str(input_pdf),
    ])
    _assert_no_pdfx_downgrade(gs_output)
    _assert_pdf(output_pdf, "press")
    _assert_pdfx(output_pdf)


def to_proof(
    input_pdf: Path,
    output_pdf: Path,
    *,
    dpi: int = 150,
    gs_binary: Optional[str] = None,
) -> None:
    """
    Produce the reviewer's proof: downsampled images, linearized for fast
    web view. Deliberately NOT the press file -- smaller and faster to open,
    and not something anyone should mistake for vendor-ready output.
    """
    gs = gs_binary or find_binary()
    if gs is None:
        raise GhostscriptError("ghostscript binary not found on PATH")

    _run([
        gs,
        "-dBATCH",
        "-dNOPAUSE",
        "-sDEVICE=pdfwrite",
        "-dPDFSETTINGS=/ebook",
        "-dDownsampleColorImages=true",
        "-dDownsampleGrayImages=true",
        f"-dColorImageResolution={dpi}",
        f"-dGrayImageResolution={dpi}",
        "-dFastWebView=true",
        f"-sOutputFile={output_pdf}",
        str(input_pdf),
    ])
    _assert_pdf(output_pdf, "proof")
